### ISSUE TITLE
The crcready option appears to be bugged

### ISSUE THREAD

**Issue by david-simoes-93** [vtex-soft/texsupport.iospress-isp#1]
Trying the 'crcready' option 

    \documentclass[crcready]{iosart2x}
 
on my machine and on OverLeaf both cause this

![crcready](https://user-images.githubusercontent.com/9117323/79877077-b70b3000-83e3-11ea-8d99-abf83920dc11.png)

And on subsequent pages, line numbers are still found. How can this be fixed?

**Comment by mingiss** [comment]
The option [crcready] has been fixed.
Sorry for late response.
